---
- id: "blended"
  formatName: "Blended"
  styles:
      - path: "../build/blended/web"
        name: "Web - Blended"
- id: "books"
  formatName: "Books"
  styles:
      - path: "../build/books/web"
        name: "Web - Books"
- id: "capi-multiple-hosted"
  formatName: "cAPI Multiple Hosted"
  styles:
      - path: "../build/capi-multiple-hosted/web"
        name: "Web - cAPI Multiple Hosted"
- id: "capi-multiple-paidfor"
  formatName: "cAPI Multiple Paidfor"
  styles:
      - path: "../build/capi-multiple-paidfor/app"
        name: "App - cAPI Multiple Paidfor"
      - path: "../build/capi-multiple-paidfor/web"
        name: "Web - cAPI Multiple Paidfor"
- id: "capi-multiple-supported"
  formatName: "cAPI Multiple Supported"
  styles:
      - path: "../build/capi-multiple-supported/web"
        name: "Web - cAPI Multiple Supported"
- id: "capi-single-paidfor"
  formatName: "cAPI Single Paidfor"
  styles:
      - path: "../build/capi-single-paidfor/web"
        name: "Web - cAPI Single Paidfor"
- id: "capi-single-supported"
  formatName: "cAPI Single Supported"
  styles:
      - path: "../build/capi-single-supported/web"
        name: "Web - cAPI Single Supported"
- id: "fabric"
  formatName: "Fabric"
  styles:
      - path: "../build/fabric/amp"
        name: "AMP - Fabric"
      - path: "../build/fabric/app"
        name: "App - Fabric"
      - path: "../build/fabric/web"
        name: "Web - Fabric"
- id: "fabric-custom"
  formatName: "Fabric Custom"
  styles:
      - path: "../build/fabric-custom/web"
        name: "Web - Fabric Custom"
- id: "fabric-expandable"
  formatName: "Fabric Expandable"
  styles:
      - path: "../build/fabric-expandable/web"
        name: "Web - Fabric Expandable"
- id: "fabric-video"
  formatName: "Fabric Video"
  styles:
      - path: "../build/fabric-video/amp"
        name: "AMP - Fabric Video"
      - path: "../build/fabric-video/app"
        name: "App - Fabric Video"
      - path: "../build/fabric-video/web"
        name: "Web - Fabric Video"
- id: "fabric-video-expandable"
  formatName: "Fabric Video Expandable"
  styles:
      - path: "../build/fabric-video-expandable/web"
        name: "Web - Fabric Video Expandable"
- id: "facebook"
  formatName: "Facebook"
  styles:
      - path: "../build/facebook/web"
        name: "Web - Facebook"
- id: "frame"
  formatName: "Frame"
  styles:
      - path: "../build/frame/amp"
        name: "AMP - Frame"
      - path: "../build/frame/app"
        name: "App - Frame"
      - path: "../build/frame/web"
        name: "Web - Frame"
- id: "gimbap"
  formatName: "Gimbap"
  styles:
      - path: "../build/gimbap/web"
        name: "Web - Gimbap"
- id: "gimbap-rich-media"
  formatName: "Gimbap Rich Media"
  styles:
      - path: "../build/gimbap-rich-media/web"
        name: "Web - Gimbap Rich Media"
- id: "gimbap-simple"
  formatName: "Gimbap Simple"
  styles:
      - path: "../build/gimbap-simple/web"
        name: "Web - Gimbap Simple"
- id: "glabs-inline"
  formatName: "Glabs Inline"
  styles:
      - path: "../build/glabs-inline/web"
        name: "Web - Glabs Inline"
- id: "glabs-left"
  formatName: "Glabs Left"
  styles:
      - path: "../build/glabs-left/web"
        name: "Web - Glabs Left"
- id: "glabs-native-traffic-driver"
  formatName: "Glabs Native Traffic Driver"
  styles:
      - path: "../build/glabs-native-traffic-driver/amp"
        name: "AMP - Glabs Native Traffic Driver"
      - path: "../build/glabs-native-traffic-driver/app"
        name: "App - Glabs Native Traffic Driver"
      - path: "../build/glabs-native-traffic-driver/web"
        name: "Web - Glabs Native Traffic Driver"
- id: "google"
  formatName: "Google"
  styles:
      - path: "../build/google/web"
        name: "Web - Google"
- id: "hosted-native-traffic-driver"
  formatName: "Hosted Native Traffic Driver"
  styles:
      - path: "../build/hosted-native-traffic-driver/amp"
        name: "AMP - Hosted Native Traffic Driver"
      - path: "../build/hosted-native-traffic-driver/web"
        name: "Web - Hosted Native Traffic Driver"
- id: "jobs"
  formatName: "Jobs"
  styles:
      - path: "../build/jobs/web"
        name: "Web - Jobs"
- id: "manual-inline"
  formatName: "Manual Inline"
  styles:
      - path: "../build/manual-inline/web"
        name: "Web - Manual Inline"
- id: "manual-inline-book"
  formatName: "Manual Inline Book"
  styles:
      - path: "../build/manual-inline-book/web"
        name: "Web - Manual Inline Book"
- id: "manual-inline-event"
  formatName: "Manual Inline Event"
  styles:
      - path: "../build/manual-inline-event/web"
        name: "Web - Manual Inline Event"
- id: "manual-multiple"
  formatName: "Manual Multiple"
  styles:
      - path: "../build/manual-multiple/web"
        name: "Web - Manual Multiple"
- id: "manual-multiple-hosted"
  formatName: "Manual Multiple Hosted"
  styles:
      - path: "../build/manual-multiple-hosted/web"
        name: "Web - Manual Multiple Hosted"
- id: "manual-multiple-membership"
  formatName: "Manual Multiple Membership"
  styles:
      - path: "../build/manual-multiple-membership/web"
        name: "Web - Manual Multiple Membership"
- id: "manual-multiple-soulmates"
  formatName: "Manual Multiple Soulmates"
  styles:
      - path: "../build/manual-multiple-soulmates/web"
        name: "Web - Manual Multiple Soulmates"
- id: "manual-single"
  formatName: "Manual Single"
  styles:
      - path: "../build/manual-single/web"
        name: "Web - Manual Single"
- id: "revealer"
  formatName: "Revealer"
  styles:
      - path: "../build/revealer/web"
        name: "Web - Revealer"
- id: "soulmates"
  formatName: "Soulmates"
  styles:
      - path: "../build/soulmates/web"
        name: "Web - Soulmates"
- id: "travel"
  formatName: "Travel"
  styles:
      - path: "../build/travel/web"
        name: "Web - Travel"
