name: CI
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches-ignore:
      - 'gh-pages'
jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: guardian/actions-setup-node@main

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Lint files
        run: yarn lint

  types:
    name: Typescript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: guardian/actions-setup-node@main

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Check typescript
        run: yarn tsc
